### ISSUE TITLE
Import errors with pymedphys 0.39.3 and pylinac 2.3.2 in Python 3.10

### ISSUE THREAD

**Issue by pylonsarenice** [pymedphys/pymedphys#1785]
I've been trying to install pymedphys 0.39.3 with Python 3.10.7 [1] but am getting errors "cannot import name 'Iterable' from 'collections'" from pylinac 2.3.2, i.e. the version of pylinac specified in https://github.com/pymedphys/pymedphys/blob/v0.39.3/requirements.txt.

This seems to be a common error when running pre-Python 3.10 code on 3.10 (see e.g. https://stackoverflow.com/a/72032097). Locally I worked around this my installing the latest version of pylinac (3.7.1) which works with Python 3.10. 

pylinac 3.2.0 is the earliest version of pylinac which explicitly lists Python 3.10 in the supported languages on PyPi https://pypi.org/project/pylinac/3.2.0/. 

I'm not sure how you determine exactly which versions to require but hope this is useful info. Best regards and thanks for the great tool.

[1] I wanted to test the fix to https://github.com/pymedphys/pymedphys/issues/1592 and use pymedphys using our current default version of Python.

**Comment by SimonBiggs** [comment]
Thanks for the detailed issue report. This should be quite fixable. Not in a position to jump on it right now though. Might you be interested if I supported you in making the fix in about a week or two from now?

**Comment by SimonBiggs** [comment]
@Matthew-Jennings, I've been trying to run updates on this and am hitting issues on Windows with numba versions for Python 3.10.

Might we be able to set up the gamma code to use the `interpolate` library if it is found, but if it is not found, have it automatically fall-back to using the original scipy? 

In order to support upgrading to Python 3.10 I am considering taking interpolate out of the `user` deps option and have a separate `speed-ups` option

**Comment by Matthew-Jennings** [comment]
Could you please elaborate? My first reaction to question whether there's a better solution...

It seems to me that `numba` is a package we'll generally want to support, and the corresponding pin for `numba` in EconForge's `interpolation` is simply ">=0.47"`. Not unreasonable, right?

[In turn, `numba` appears to support Python 3.7–3.10, and Numpy 1.18-1.23.](https://numba.readthedocs.io/en/stable/user/installing.html#compatibility)

**Comment by SimonBiggs** [comment]
Might you be able to see if you can upgrade to Python 3.10 on Windows?
(While removing the pylinac pin)
